# Generated by Django 5.1.3 on 2024-11-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_category_alter_blogpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
